<?php
echo'
<br><button onclick="history.back()">REGRESAR</button>
<footer>
  <H6>REALIZADFO POR:KELVIN ALDRIANSANCHEZ ORTEGA<BR>
  ESPECIALIDAD EN DESARROLLO DE SFOTWARE<BR>
  INSTITUCION EDUCATIVASAN FRANCISCO DE SALES<BR>
  MAYO 20204</H6>
</footer>
</body>
</html>';
?>'